lakehouse:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'dev.duckdb'
      threads: 1
      extensions:
        - httpfs
        - parquet

    prod:
      type: duckdb
      path: 'prod.duckdb'
      threads: 4
